### ISSUE TITLE
WMAS 2018 Test Runner  vs 2020?

### ISSUE THREAD

**Issue by javierbarellano4v** [cta-wave/WMAS#74]
Is WMAS 2018 Test Runner v1.0.2 release really the release for WMAS 2020?

I'm trying to check out latest WMAS?

Thanks.

**Comment by FritzHeiden** [comment]
You can find the latest WMAS 2020 release under the [wmas2020](https://github.com/cta-wave/WMAS/tree/wmas2020) branch.

**Comment by javierbarellano4v** [comment]
Thanks Fritz!

One more question. In older READMEs, it recommends to install a Python version that is NOT 3.X. Is that still the case?

T

**Comment by JohnRiv** [comment]
For WMAS2019 & WMAS2020, Python 3.6 or higher is required

**Comment by javierbarellano4v** [comment]
Thanks John! Appreciate it.

**Comment by javierbarellano4v** [comment]
Is latest release in https://github.com/cta-wave/WMAS/releases different from https://github.com/cta-wave/WMAS/tree/wmas2020? It appears to be, just want to confirm.

**Comment by JohnRiv** [comment]
Looking at the dates, yes they are different.

@FritzHeiden that brings up a good point, it'd be useful to tag the wmas2019 and wmas2020 branches as new releases. Any reason not to just tag the head of each of those branches as `WMAS 2019 Test Runner v1.0.0` and  `WMAS 2020 Test Runner v1.0.0` ?

**Comment by FritzHeiden** [comment]
@JohnRiv I've added two [releases](https://github.com/cta-wave/WMAS/releases) accordingly.

**Comment by JohnRiv** [comment]
Thanks @FritzHeiden!

**Comment by javierbarellano4v** [comment]
Are the instructions at https://github.com/cta-wave/WMAS still valid for WMAS 2020 at https://github.com/cta-wave/WMAS/tree/wmas2020?

I don't see a config.json.

thanks.

**Comment by JohnRiv** [comment]
The docs for 2020 are at https://github.com/cta-wave/WMAS/blob/wmas2020/tools/wave/docs/usage/usage.md (linked to from https://github.com/cta-wave/WMAS/tree/wmas2020#command-line-tools)

**Comment by javierbarellano4v** [comment]
Thanks @JohnRiv !

**Comment by louaybassbouss** [comment]
I propose to provide a landing page (README in the master branch) for this repository similar to the landing page of [WMAS-deploy](https://github.com/cta-wave/WMAS-deploy/) repository. We can add Links to dedicated WMAS branches (WMAS2017, ... WMAS2020) and corresponding documentations. We can also add links to the corresponding docker deployment branch in [WMAS-deploy](https://github.com/cta-wave/WMAS-deploy/). wdyt?

**Comment by JohnRiv** [comment]
@louaybassbouss Sounds good. On the HATF call today we agreed you can move forward with those changes.

**Comment by javierbarellano4v** [comment]
At https://github.com/cta-wave/WMAS-deploy/ is the repo for creating docker image for the server in an VM similar to DPCTF test runner

Then, at https://github.com/cta-wave/WMAS/tree/wmas2020, it describes how to launch wpt via python. Confused.

Assuming that https://github.com/cta-wave/WMAS/tree/wmas2020-tests are the tests which would be downloaded. 

Apologize for all the questions...

**Comment by louaybassbouss** [comment]
@javierbarellano4v WMAS-deploy creates a docker image of the WMAS Test Runner there is no need to setup it manually as stated in WMAS repository. The WMAS-deploy is a new addition we implemented recently to make deployment easier. WMAS-deploy will fetch the Test Runner code from the corresponding branch of WMAS repository.

**Comment by javierbarellano4v** [comment]
Gotcha, I was close.  Thanks @louaybassbouss

**Comment by javierbarellano4v** [comment]
I've been trying to build the docker image in a Linux VM (Ubuntu 20.04).

I've been running into error which I'm not sure can be attributed to my environment and setup.

Invoking the following:   sudo ./build.sh wmas2020 latest

Generates the following, here is an excerpt:

Step 17/28 : RUN npm install --global https://github.com/cta-wave/wptreport.git#main
 ---> Running in c94d3d85ff03
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/cta-wave/wptreport.git
npm ERR!
npm ERR!
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
npm ERR!    /root/.npm/_logs/2022-07-24T22_25_14_669Z-debug.log
The command '/bin/sh -c npm install --global https://github.com/cta-wave/wptreport.git#main' returned a non-zero code: 1

Any suggestions?
Thank you.

**Comment by javierbarellano4v** [comment]
to follow up,  still having problems..

Is there a particular version of npm? or node.js? that I need.

**Comment by javierbarellano4v** [comment]
just to add.. I've tried in Ubuntu and in WSL on Windows 10.. get same error.

**Comment by louaybassbouss** [comment]
@javierbarellano4v  we are checking this and let you know very soon

**Comment by javierbarellano4v** [comment]
Thank you @louaybassbouss

**Comment by louaybassbouss** [comment]
@javierbarellano4v we can reproduce the issue and we are working on a fix

**Comment by javierbarellano4v** [comment]
Great @louaybassbouss .Thanks all!

**Comment by FritzHeiden** [comment]
@javierbarellano4v I pushed a fix for this. Please try running it again!

**Comment by javierbarellano4v** [comment]
Thanks @FritzHeiden! I greatly appreciate it!

**Comment by javierbarellano4v** [comment]
Successfully built image!  Thanks again!

In terms of launching, it appears that script launches docker image automatically upon build completion.

Is the access still  http://<ip address>:8050/  to get to tests? Anything else to configure to access tests?

Thank you!

**Comment by javierbarellano4v** [comment]
http://server-ip-address:8050/

**Comment by javierbarellano4v** [comment]
I was able to build image as I stated but now I launch docker I get the following error:

parallels@parallels-Parallels-Virtual-Platform:~/WMAS-deploy-wmas2020$ sudo docker-compose up -d
Starting wmas2020 ... 
Starting wmas2020 ... error

ERROR: for wmas2020  Cannot start service wmats2018: driver failed programming external connectivity on endpoint wmas2020 (4153c4655e58af878e0cb43907901b0bf506039fa76bb83b1f5ccb9fc922425d): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use

ERROR: for wmats2018  Cannot start service wmats2018: driver failed programming external connectivity on endpoint wmas2020 (4153c4655e58af878e0cb43907901b0bf506039fa76bb83b1f5ccb9fc922425d): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by javierbarellano4v** [comment]
Just to update:   

I tried to launch the container using the Docker for Desktop GUI in WSL. 

After a long interval, the following:


[3:43 PM] Javier Arellano
cp: target 'results' is not a directory
INFO:manifest:Updating manifest
cp: target 'results' is not a directory
INFO:manifest:Updating manifest
cp: target 'results' is not a directory
INFO:manifest:Updating manifest
[2022-08-01 20:27:24,414 None on port 58677] INFO - Starting http server on web-platform.test:58677
[2022-08-01 20:28:47,111 None on port 58677] INFO - Stopped http server on web-platform.test:58677
[2022-08-01 20:28:48,106 http on port 8000] INFO - Starting http server on web-platform.test:8000
[2022-08-01 20:28:48,553 http on port 42409] INFO - Starting http server on web-platform.test:42409
[2022-08-01 20:28:49,083 http-private on port 45299] INFO - Starting http server on web-platform.test:45299
[2022-08-01 20:28:52,678 http-public on port 47911] INFO - Starting http server on web-platform.test:47911
[2022-08-01 20:28:53,697 https on port 8443] INFO - Starting https server on web-platform.test:8443
[2022-08-01 20:28:54,239 https on port 8444] INFO - Starting https server on web-platform.test:8444
[2022-08-01 20:28:54,669 https-private on port 59371] INFO - Starting https server on web-platform.test:59371
[2022-08-01 20:28:55,148 https-public on port 52239] INFO - Starting https server on web-platform.test:52239
[2022-08-01 20:28:55,881 ws on port 55921] INFO - Create socket on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 55921))
[2022-08-01 20:28:55,882 ws on port 55921] INFO - Bind on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 55921))
[2022-08-01 20:28:55,887 ws on port 55921] INFO - Listen on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 55921))
[2022-08-01 20:29:00,681 wss on port 44317] INFO - Create socket on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 44317))
[2022-08-01 20:29:00,800 wss on port 44317] INFO - Bind on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 44317))
[2022-08-01 20:29:00,821 wss on port 44317] INFO - Listen on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 44317))
[2022-08-01 20:29:01,323 h2 on port 9000] INFO - Starting http2 server on web-platform.test:9000

Is the expected behavior? 

If this is correct, which port should I open an URL to?

**Comment by FritzHeiden** [comment]
> ERROR: for wmats2018 Cannot start service wmats2018: driver failed programming external connectivity on endpoint wmas2020 (4153c4655e58af878e0cb43907901b0bf506039fa76bb83b1f5ccb9fc922425d): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use ERROR: Encountered errors while bringing up the project.

The docker image has a DNS server bundled, so when you try to create a container while already having a DNS server running you get this port binding error. You can remove/comment the binding of port 53 in the docker-compose.yml if you don't intend to use the bundled DNS server.


> Attempted in WSL on Windows and yielded on the following:
> 
> javier@JAVIERARELLA81A:/mnt/c/WMAS-deploy-wmas2020$ sudo docker-compose up -d [+] Running 0/1 ⠿ wmats2018 Error 5.2s Error response from daemon: pull access denied for wmas2020, repository does not exist or may require 'docker login': denied: requested access to the resource is denied javier@JAVIERARELLA81A:/mnt/c/WMAS-deploy-wmas2020$
> 
> if that helps.... thanks.

This looks like the docker instance you are using does not have access to the image. Either you didn't build it or you built it using a different docker instance.

> If this is correct, which port should I open an URL to?

This actually looks correct. Use port 8000 to access the landing page.

**Comment by javierbarellano4v** [comment]
I tried: web-platfom.test:8000 in the WSL instance, and page didn't load.

Maybe I need to do additional configuration.

**Comment by javierbarellano4v** [comment]
No port listed upon inspection of WMAS2020 docker container

![wmas2020 container](https://user-images.githubusercontent.com/97479879/183131146-37336ec2-cbba-4a92-9647-4c4176a5f4fb.png)

**Comment by louaybassbouss** [comment]
@javierbarellano4v is there any chance to test first on linux. We highly recommend using linux with docker.

**Comment by javierbarellano4v** [comment]
Right. Ok, I'll focus on Linux deployment going forward. 

Thanks.

**Comment by louaybassbouss** [comment]
> Right. Ok, I'll focus on Linux deployment going forward.
> 
> Thanks.

Thanks @javierbarellano4v let us know if you face issues we are happy to help

**Comment by javierbarellano4v** [comment]
Spun up the linux (Ubuntu) deployed docker container for WMAS2020:latest

Not sure if this is a misconfiguration on my part in my environment - maybe I can get some insight. Thank you.

<img width="1478" alt="Screen Shot 2022-08-10 at 12 24 13 PM" src="https://user-images.githubusercontent.com/97479879/183978670-29b9a880-8b3b-4e19-ba77-5b35e7d3e5d1.png">

**Comment by FritzHeiden** [comment]
@javierbarellano4v I encountered the problem before, however, this should be fixed with the latest changes. Did you pull the latest changes from github? What command did you use to build the image? Could you post the build log?

We may also have a call if you can't get it to work.

**Comment by javierbarellano4v** [comment]
I eliminated the ua-parser error.

Now I'm able to get to landing page using my host's IP address like: http:/<ip-address>:8000/_wave/index.html 

But, when I select to run the test cases in the configuration page after the landing page, it errors, can't find "web-plaform.test:8000/..." like the 2nd attached snapshot.

------

See attachments.

![0d484db4-488a-4b90-b17b-8d90958842dd](https://user-images.githubusercontent.com/97479879/184727264-2733847d-6590-40d1-aa33-2410aa428268.jpg)



![801a86d6-c029-44c0-8330-83ad33ee71b3](https://user-images.githubusercontent.com/97479879/184727285-a48f7c64-6b72-4c14-95e1-9e30ec663839.jpg)

**Comment by louaybassbouss** [comment]
@javierbarellano4v this looks good the issue you are facing is related to the domain web-platform.test. The WPT test runner uses more than 100 different subdomains and this is why we included a DNS Server to resolve these domains. What you need to do is to use the IP of the test runner  as DNS IP on the device under test. This way, all domains/subdomains used by the test runner can be resolved. @FritzHeiden please check if this is not documented and update documentation if needed.

**Comment by louaybassbouss** [comment]
@javierbarellano4v this looks good the issue you are facing is related to the domain web-platform.test. The WPT test runner uses more than 100 different subdomains and this is why we included a DNS Server to resolve these domains. What you need to do is to use the IP of the test runner  as DNS IP on the device under test. This way, all domains/subdomains used by the test runner can be resolved. @FritzHeiden please check if this is not documented and update documentation if needed.

**Comment by FritzHeiden** [comment]
@javierbarellano4v I've added documentation on how to setup the required domains in the [WMAS-deploy README.md](https://github.com/cta-wave/WMAS-deploy/tree/wmas2020#access-test-runner)

**Comment by javierbarellano4v** [comment]
@louaybassbouss @FritzHeiden I will take a look at this next. Thank you very much.

**Comment by javierbarellano4v** [comment]
I discovered when I tried to run with built-in DNS Server at port 53, I'm not able to because Ubuntu has systemd-r assigned to port 53.

**Comment by FritzHeiden** [comment]
Port 53 is the default port for any DNS resolving service. You can stop the service by running `systemctl stop systemd-resolved`

**Comment by louaybassbouss** [comment]
@javierbarellano4v FYI the domains/subdomains used by the Test Runner are listed in [WMAS-deploy/blob/wmas2020/docker-compose.yml](https://github.com/cta-wave/WMAS-deploy/blob/wmas2020/docker-compose.yml).

**Comment by javierbarellano4v** [comment]
@FritzHeiden 

Where I stand...

1. Uncomment line of the port number in docker-compose.yml
2.  Set the TEST_RUNNER_IP to the host address, e.g., 192.168.1.10, in docker-compose.yml
3. 'sudo docker-compose up'
4.  Once up, go to 192.168.1.10:8000/_wave/index.html
5. Select a testcase from the list to run.
6. In a separate tab (same host) the opening of  "web-platform.test:8000/.... " ultimately fails.

**Comment by javierbarellano4v** [comment]
I tried "web-platform.test:8000/_wave/index.html in step #4 above... still no success.

Thank you.

**Comment by javierbarellano4v** [comment]
![452be32d-d4e2-4f76-88a1-da015e4878b9](https://user-images.githubusercontent.com/97479879/185466082-b5812685-14ab-4746-83e1-92960c0e3954.jpg)

**Comment by javierbarellano4v** [comment]
@FritzHeiden 

> We may also have a call if you can't get it to work.

I'd like to get on a call to work through this this coming week. Thank you.

**Comment by FritzHeiden** [comment]
> @FritzHeiden
> 
> Where I stand...
> 
>     1. Uncomment line of the port number in docker-compose.yml
> 
>     2. Set the TEST_RUNNER_IP to the host address, e.g., 192.168.1.10, in docker-compose.yml
> 
>     3. 'sudo docker-compose up'
> 
>     4. Once up, go to 192.168.1.10:8000/_wave/index.html
> 
>     5. Select a testcase from the list to run.
> 
>     6. In a separate tab (same host) the opening of  "web-platform.test:8000/.... " ultimately fails.

Did you configure the DUT to also use the DNS server? You have to enter the test runner IP in the DUTs network configuration as DNS server.


> @FritzHeiden
> 
> > We may also have a call if you can't get it to work.
> 
> I'd like to get on a call to work through this this coming week. Thank you.

I am available today and tomorrow.

**Comment by javierbarellano4v** [comment]
Let's do tomorrow. Would Zoom work for you? 

What's a good time slots or range of time tomorrow, given the time difference?

**Comment by javierbarellano4v** [comment]
@FritzHeiden Had network issues this morning. Pardon the snafu. 

Are you available tomorrow? Thank you for your patience.

**Comment by javierbarellano4v** [comment]
@FritzHeiden  Thanks. Let's aim for Tuesday (8/30). Preferred time slots?

**Comment by FritzHeiden** [comment]
@javierbarellano4v Don't have any preferred time slots, I am available until 7 PM CEST

**Comment by javierbarellano4v** [comment]
@FritzHeiden please send me your email address so I can send a Zoom link.

This would be for tomorrow (9/1) though.

Thank you.

**Comment by FritzHeiden** [comment]
fritz.heiden@fokus.fraunhofer.de

**Comment by javierbarellano4v** [comment]
Thanks @FritzHeiden !

**Comment by JohnRiv** [comment]
Landing page has been added to README: https://github.com/cta-wave/WMAS

Javier and Fritz will collaborate offline.
